name: Build project page

on:
  push:
    branches: ["website"]

permissions:
  contents: read

concurrency:
  group: "website-build"
  cancel-in-progress: true

env:
  NEXT_PUBLIC_REPO_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build static site
        run: npm run build
